INSERT INTO clientes (id, nombre, apellido, forma_pago, creado_en, editado_en) VALUES (1,'Daniel','Ramirez','credito',NULL,NULL),(2,'Juana','Arco','efectivo',NULL,NULL),(3,'Pablo','Juarez','paypal',NULL,NULL),(4,'Maria','Cruz','credito',NULL,NULL),(5,'Luisina','Reyes','debito',NULL,NULL),(6,'lulu','guerrero','credito',NULL,NULL),(10,'Maria','Sotelo','paypal',NULL,NULL),(11,'Pedro','Picapiedra','paypal plus','2024-04-25 09:47:52','2024-04-25 09:48:22');
INSERT INTO alumnos (id, nombre, apellido) VALUES(1, 'Jose', 'Cordero');
INSERT INTO alumnos (id, nombre, apellido) VALUES(2, 'Carla', 'Gonzalez');
INSERT INTO cursos (id, titulo, profesor) VALUES(1, 'Javascript', 'Andres');
INSERT INTO cursos (id, titulo, profesor) VALUES(2, 'Angular', 'Andres');
INSERT INTO direcciones (calle, numero) VALUES('Av cien metros', 10);
INSERT INTO direcciones (calle, numero) VALUES('Av politecnico', 20);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES (1,1);
INSERT INTO tbl_clientes_direcciones(id_cliente, id_direccion) VALUES (1,2);
INSERT INTO clientes_detalles (prime, puntos_acumulados, cliente_detalle_id) VALUES (1, 8000, 1);
INSERT INTO tbl_alumnos_cursos (alumno_id, curso_id) VALUES (1,1);
INSERT INTO tbl_alumnos_cursos (alumno_id, curso_id) VALUES (1,2);